name: ducktape
lang: python
lang_version: '3.13'
git:
  enable: true
sonarqube:
  enable: true
github:
  enable: true
  repo_name: confluentinc/ducktape
renovatebot:
  enable: true
  automerge:
    enable: false
semaphore:
  enable: true
  pipeline_enable: false
  branches:
  - master
  - 0.13.x
  - 0.12.x
  - 0.11.x
  - 0.10.x
  - 0.9.x
  - 0.8.x
  - 0.7.x
