name: ducktape
lang: unknown
lang_version: unknown
git:
  enable: true
sonarqube:
  enable: false
github:
  enable: true
  repo_name: confluentinc/ducktape
semaphore:
  enable: true
  pipeline_enable: false
  branches:
  - master
  - 0.11.x
  - 0.10.x
  - 0.9.x
  - 0.8.x
  - 0.7.x